// Code generated by Kitex v0.8.0. DO NOT EDIT.
package userservices

import (
	server "github.com/cloudwego/kitex/server"
	user_service "grpc_demo/kitex_gen/user_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler user_service.UserServices, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
